### ISSUE TITLE
Install mmcv-full failed based on pytorch image with error msg `no kernel image is available`

### ISSUE THREAD

**Issue by del-zhenwu** [open-mmlab/mmcv#1413]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

nvidia-smi info:
```
GPU version: v100, cuda:11.2, nvidia-driver:460
```
dockerfile used:
```
ARG PYTORCH="1.6.0"
ARG CUDA="10.1"
ARG CUDNN="7"

FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel
ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV FORCE_CUDA="1"
ENV MMCV_CUDA_ARGS="-gencode=arch=compute_61,code=sm_61"
...
```
I have found the solution, by changing the following
```
ENV MMCV_CUDA_ARGS="-gencode=arch=compute_61,code=sm_61"
```
to 
```
ENV MMCV_CUDA_ARGS="-gencode=arch=compute_70,code=sm_70"
```

My suggestion is:
1. Add some comments in Dockerfile & .github/workflow/build.yml
```
  build_cu101:
    runs-on: ubuntu-18.04
    container:
      image: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel
    env:
      FORCE_CUDA: 1
      # update the MMCV_CUDA_ARGS here or just remove the following line
      MMCV_CUDA_ARGS: -gencode=arch=compute_61,code=sm_61
```
2. Add some docs for docker installation
